apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: kburh-java-deployment 
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: kburh-java
  template:
    metadata:
      labels:
        app: kburh-java
    spec:
      containers:
        - name: kburh-java-container
          image: burhankhair/kburh-java
